import type { Metadata } from 'next';
import { Coda, Inter } from 'next/font/google';
import './globals.css';
import Header from './Common/Header';
import Footer from './Common/Footer';
import 'react-slideshow-image/dist/styles.css';

const CodaFont = Coda({
  weight: '400',
  subsets: ['latin'],
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={CodaFont.className}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        />
      </head>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
